version: 3

services:
  # More info at:
  # https://giscience.github.io/openrouteservice/installation/Installation-and-Usage.html

  open-route-service:
    container_name: "unitac_open-route-service"
    image: openrouteservice/openrouteservice:latest
    user: "${ORS_UID:-0}:${ORS_GID:-0}"
    volumes:
      - ./data/graphs:/ors-core/data/graphs
      - ./data/elevation_cache:/ors-core/data/elevation_cache
      - ./data/conf:/ors-conf
      #- ./data/import/your_osm.pbf:/ors-core/data/osm_file.pbf
      - ./logs/ors:/var/log/ors
      - ./logs/tomcat:/usr/local/tomcat/logs
    env_file:
      - ./configs/open-route-service
