version: '3'
services:
  proxy:
    image: nginx:stable
    ports:
      - '3000:80'
    volumes:
      - ./services/proxy/configs/default.conf:/etc/nginx/conf.d/default.conf
      - ./services/proxy/configs/vhosts:/etc/nginx/conf.d/sites-enabled

  postgis:
    image: postgis/postgis:14-master
    volumes:
      - ./services/postgis/data:/var/lib/postgresql/data
    env_file:
      - ./services/postgis/config

  pgadmin:
    image: dpage/pgadmin4:5
    depends_on:
      - postgis
    ports:
      - "8888:80"
    env_file:
      - ./services/pgadmin/config

  cosi:
    hostname: cosi
    image: node:16.16
    user: node
    depends_on:
      - proxy
    command: 'npx serve ./dist/temp'
    working_dir: /home/node/workspace
    volumes:
      - $REPO_PATH_MASTERPORTAL:/home/node/workspace
      - $REPO_PATH_COSI:/home/node/workspace/addons
      - $REPO_PATH_MPPORTALCONFIGS/cosi:/home/node/workspace/portal/cosi
    env_file:
      - ./services/cosi/config

  dipas_backend:
    build:
      context: ./services/dipas
    working_dir: /app
    user: root
    command: bash -c 'apache2ctl start && tail -f -n1 /var/log/apache2/other_vhosts_access.log'
    depends_on:
      - proxy
      - postgis
    volumes:
      - $REPO_PATH_DIPAS:/app
      #- ./services/dipas/configs/php:/etc/php/8.2/apache2/conf.d:ro
      - ./services/dipas/configs/php/99-pg.ini:/etc/php/8.2/apache2/conf.d/99-pg.ini:ro
      - ./services/dipas/configs/php/99-php.ini:/etc/php/8.2/apache2/conf.d/99-php.ini:ro
      - ./services/dipas/configs/apache/dipas_vhost.conf:/etc/apache2/sites-available/dipas.conf:ro
      - ./services/dipas/configs/drupal.database-settings.php:/app/config/drupal.database-settings.php
    env_file:
      - ./services/dipas/configs/backend_php

  dipas_frontend:
    image: node:10
    user: node
    depends_on:
      - proxy
      - dipas_backend
    command: 'npm run serve'
    working_dir: /home/node/workspace
    volumes:
      - $REPO_PATH_DIPAS:/home/node/workspace:delegated

  geoserver:
    container_name: "unitac_geoserver"
    image: kartoza/geoserver:latest
    ports:
      - "8080"
    depends_on:
      - postgis
    volumes:
      - ./services/geoserver/data:/opt/geoserver/data_dir
    env_file:
      - ./services/geoserver/config

  #open_route_service:
  #  container_name: "unitac_open-route-service"
  #  image: openrouteservice/openrouteservice:latest
  #  user: "${ORS_UID:-0}:${ORS_GID:-0}"
  #  volumes:
  #    - ./data/graphs:/ors-core/data/graphs
  #    - ./data/elevation_cache:/ors-core/data/elevation_cache
  #    - ./data/conf:/ors-conf
  #    #- ./data/import/your_osm.pbf:/ors-core/data/osm_file.pbf
  #    - ./logs/ors:/var/log/ors
  #    - ./logs/tomcat:/usr/local/tomcat/logs
  #  env_file:
  #    - ./services/open-route-service/config
