services:
  masterportal:
    extends:
      file: services/masterportal/masterportal.yaml
      service: masterportal

  cosi:
    extends:
      file: services/cosi/cosi.yaml
      service: cosi

  dipas:
    extends:
      file: services/dipas/dipas.yaml
      service: dipas

  geoserver:
    extends:
      file: services/geoserver/geoserver.yaml
      service: geoserver

  open-route-service:
    extends:
      file: services/open-route-service/open-route-service.yaml
      service: open-route-service

  #osmtool:
  #  extends:
  #    file: services/osmtool/osmtool.yaml
  #    service: osmtool
