FROM bitnami/php-fpm:8.0.9

RUN apt-get update && apt-get install -y \
		curl \
		git \
		vim \
		wget \
		postgresql-client

#Install composer
RUN wget https://getcomposer.org/installer
RUN mv installer composer-setup.php
RUN	php composer-setup.php
RUN	mv composer.phar /usr/local/bin/composer
RUN	php -r "unlink('composer-setup.php');"
