services:
  masterportal:
    container_name: "unitac_cosi"
    image: node:16.16
    user: node
    command: 'npm start'
    working_dir: /home/node/workspace
    volumes:
      - ./code:/home/node/workspace
    env_file:
      - ./configs/masterportal
